[phases.setup]
nixPkgs = [
  "cmake",
  "gcc",
  "gnumake",
  "pkg-config",
  "python311Packages.pip",
  "python311", # add the python interpreter
]

[phases.install]
cmds = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". venv/bin/activate"
]

[start]
cmd = ". venv/bin/activate && python app.py"