#nixpacks.toml

[phases.setup]
nixPkgs = [
  "cmake",
  "gcc",
  "gnumake",
  "pkg-config",
  "libffi",
  "zlib",
  "openssl",
  "python311Packages.pip"  # Adjust based on your Python version
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app"